#import bevy_pbr::mesh_view_bindings::view

#ifdef DEPTH_PREPASS
#import bevy_pbr::prepass_utils
#endif

// Slot 0: Quad mesh vertices (pos+uv)
// Slot 1: Face instances generated by compute

struct VoxelUniform {
    model: mat4x4<f32>,
    chunk_base_world: vec4<f32>, // xyz = base world, w = voxel_size
    wire_params: vec4<f32>,
};

@group(2) @binding(0) var<uniform> u: VoxelUniform;
@group(2) @binding(1) var<storage, read> palette: array<vec4<f32>>;

struct VertexInput {
    @location(0) quad_pos: vec3<f32>, // [0..1] quad in XY plane
    @location(1) quad_uv: vec2<f32>,
};

struct InstanceInput {
    @location(2) cell_xyz: vec3<i32>, // voxel cell coord within chunk (0..CHUNK_SIZE-1)
    @location(3) dir: u32,            // 0..5
    @location(4) pi: u32,             // palette index
    @location(5) lod: u32,            // 0..3 (scale = 2^lod)
    @location(6) span_u: u32,         // quad span along U axis (>=1)
    @location(7) span_v: u32,         // quad span along V axis (>=1)
};

struct VertexOutput {
    @builtin(position) clip_position: vec4<f32>,
    @location(0) uv: vec2<f32>,
    @location(1) color: vec4<f32>,
    @location(2) normal_ws: vec3<f32>,
    @location(3) span: vec2<f32>,
};

fn edge_mask(uv: vec2<f32>, px: f32) -> f32 {
    let d = min(min(uv.x, 1.0 - uv.x), min(uv.y, 1.0 - uv.y));
    let uv_aa = fwidth(uv);
    let aa = max(uv_aa.x, uv_aa.y);
    let aa_safe = max(aa, 0.0001);
    let d_px = d / aa_safe;
    let face_px = 1.0 / aa_safe;
    let eff_px = min(px, face_px * 0.08);
    return 1.0 - smoothstep(eff_px, eff_px + 1.0, d_px);
}

fn grid_mask(uv: vec2<f32>, span: vec2<f32>, px: f32) -> f32 {
    let s = max(span, vec2<f32>(1.0));
    let p = uv * s; // 0..span in voxel units
    let f = fract(p);
    let dist = min(f, 1.0 - f); // distance to nearest grid line (integer boundary)
    let d = min(dist.x, dist.y);
    let p_aa = fwidth(p);
    let aa = max(p_aa.x, p_aa.y);
    let aa_safe = max(aa, 0.0001);
    let d_px = d / aa_safe;
    let cell_px = 1.0 / aa_safe; // pixels per 1 voxel cell on face
    let eff_px = min(px, cell_px * 0.45);
    return 1.0 - smoothstep(eff_px, eff_px + 1.0, d_px);
}

fn face_normal(dir: u32) -> vec3<f32> {
    switch(dir) {
        case 0u: { return vec3<f32>(1.0, 0.0, 0.0); }  // +X
        case 1u: { return vec3<f32>(-1.0, 0.0, 0.0); } // -X
        case 2u: { return vec3<f32>(0.0, 1.0, 0.0); }  // +Y
        case 3u: { return vec3<f32>(0.0, -1.0, 0.0); } // -Y
        case 4u: { return vec3<f32>(0.0, 0.0, 1.0); }  // +Z
        default: { return vec3<f32>(0.0, 0.0, -1.0); } // -Z
    }
}

fn face_pos_vox(cell: vec3<i32>, dir: u32, q: vec2<f32>, span: vec2<f32>) -> vec3<f32> {
    // `q` is in [0..1] for quad coords.
    let cx = f32(cell.x);
    let cy = f32(cell.y);
    let cz = f32(cell.z);
    switch(dir) {
        case 0u: { // +X plane at x+1, spanning y/z
            return vec3<f32>(cx + 1.0, cy + q.x * span.x, cz + q.y * span.y);
        }
        case 1u: { // -X plane at x
            return vec3<f32>(cx, cy + q.x * span.x, cz + q.y * span.y);
        }
        case 2u: { // +Y plane at y+1, spanning x/z
            return vec3<f32>(cx + q.x * span.x, cy + 1.0, cz + q.y * span.y);
        }
        case 3u: { // -Y plane at y
            return vec3<f32>(cx + q.x * span.x, cy, cz + q.y * span.y);
        }
        case 4u: { // +Z plane at z+1, spanning x/y
            return vec3<f32>(cx + q.x * span.x, cy + q.y * span.y, cz + 1.0);
        }
        default: { // -Z plane at z
            return vec3<f32>(cx + q.x * span.x, cy + q.y * span.y, cz);
        }
    }
}

@vertex
fn vertex(v: VertexInput, inst: InstanceInput) -> VertexOutput {
    var out: VertexOutput;

    let voxel_size = u.chunk_base_world.w;
    let base_ws = u.chunk_base_world.xyz;
    let q = v.quad_pos.xy; // [0..1]
    let span = vec2<f32>(max(1.0, f32(inst.span_u)), max(1.0, f32(inst.span_v)));
    let pos_vox = face_pos_vox(inst.cell_xyz, inst.dir, q, span);
    let scale = f32(1u << inst.lod);
    let pos_ws = base_ws + pos_vox * voxel_size * scale;

    let world = u.model * vec4<f32>(pos_ws, 1.0);
    out.clip_position = view.clip_from_world * world;
    out.uv = v.quad_uv;
    out.span = span;

    let c = palette[inst.pi];
    out.color = vec4<f32>(c.xyz, 1.0);

    // Flat shading for now.
    out.normal_ws = face_normal(inst.dir);
    return out;
}

@fragment
fn fragment(
#ifdef MULTISAMPLED
    @builtin(sample_index) sample_index: u32,
#endif
    @builtin(front_facing) front_facing: bool,
    in: VertexOutput,
) -> @location(0) vec4<f32> {
#ifndef MULTISAMPLED
    let sample_index = 0u;
#endif

    // Very cheap lambert-ish shading to help depth perception.
    let n = normalize(in.normal_ws);
    let l = normalize(vec3<f32>(0.35, 0.85, 0.40));
    let ndl = clamp(dot(n, l) * 0.5 + 0.5, 0.0, 1.0);

    let shaded = vec4<f32>(in.color.xyz * (0.45 + 0.55 * ndl), 1.0);
    let mode = u.wire_params.y;
    let wire_px = max(u.wire_params.x, 0.0);
    let ghost = u.wire_params.z;
    let e = grid_mask(in.uv, in.span, wire_px);

    var back = select(1.0, 0.15, !front_facing && ghost > 0.5);

#ifdef DEPTH_PREPASS
    if (ghost > 0.5) {
        let geometry_depth = prepass_utils::prepass_depth(in.clip_position, sample_index);
        let wire_depth = in.clip_position.z / max(in.clip_position.w, 0.0000001);
        if (geometry_depth >= wire_depth) {
            back = min(back, 0.10);
        }
    }
#endif

    let wire_rgb = mix(shaded.xyz, vec3<f32>(0.0, 0.0, 0.0), back);
    let wire_color = vec4<f32>(wire_rgb, 1.0);

    if (mode < 0.5) {
        return shaded;
    }
    if (mode < 1.5) {
        if (e < 0.5) { discard; }
        return wire_color;
    }
    return mix(shaded, wire_color, e);
}

